import type { DemoListingRow } from "./types";

export const SHARED_LISTING_THUMB = (index: number) =>
  `/demos/_shared/listings/${index % 6}.webp`;

export const GENERIC_FALLBACK_LISTINGS: DemoListingRow[] = [
  {
    id: "listing-0",
    address: "Kerkstraat 24",
    city: "Utrecht",
    price: "€ 425.000",
    status: "Nieuw",
    statusStyle: "new",
    agent: "MV",
    agentName: "Mark de Vries",
    daysOnMarket: 5,
    thumbSrc: SHARED_LISTING_THUMB(0),
    bedrooms: 4,
    livingArea: "112 m²",
    fundaViews: 620,
    fundaPublished: true,
    websitePublished: true,
    publicationStatus: "live",
    lastSync: "Vandaag 09:15",
  },
  {
    id: "listing-1",
    address: "Laan van Meerdervoort 88",
    city: "Den Haag",
    price: "€ 589.000",
    status: "Te koop",
    statusStyle: "sale",
    agent: "SB",
    agentName: "Sophie Bakker",
    daysOnMarket: 18,
    thumbSrc: SHARED_LISTING_THUMB(1),
    bedrooms: 5,
    livingArea: "138 m²",
    fundaViews: 1102,
    fundaPublished: true,
    websitePublished: true,
    publicationStatus: "live",
    lastSync: "Vandaag 09:15",
  },
  {
    id: "listing-2",
    address: "Stationsweg 12",
    city: "Breda",
    price: "€ 375.000",
    status: "Onder bod",
    statusStyle: "bid",
    agent: "TJ",
    agentName: "Tom Jansen",
    daysOnMarket: 32,
    thumbSrc: SHARED_LISTING_THUMB(2),
    bedrooms: 3,
    livingArea: "94 m²",
    fundaViews: 890,
    fundaPublished: true,
    websitePublished: true,
    publicationStatus: "live",
    lastSync: "2 uur geleden",
  },
  {
    id: "listing-3",
    address: "Parklaan 7",
    city: "Arnhem",
    price: "€ 495.000",
    status: "Te koop",
    statusStyle: "sale",
    agent: "LK",
    agentName: "Laura Koning",
    daysOnMarket: 41,
    thumbSrc: SHARED_LISTING_THUMB(3),
    bedrooms: 4,
    livingArea: "125 m²",
    fundaViews: 540,
    fundaPublished: true,
    websitePublished: false,
    publicationStatus: "live",
    lastSync: "Gisteren",
  },
  {
    id: "listing-4",
    address: "Dorpsstraat 101",
    city: "Amersfoort",
    price: "€ 349.000",
    status: "Nieuw",
    statusStyle: "new",
    agent: "MV",
    agentName: "Mark de Vries",
    daysOnMarket: 3,
    thumbSrc: SHARED_LISTING_THUMB(4),
    bedrooms: 3,
    livingArea: "102 m²",
    fundaViews: 210,
    fundaPublished: true,
    websitePublished: true,
    publicationStatus: "live",
    lastSync: "Vandaag 11:00",
  },
];
