import type { ScrapedListing } from "@/lib/bedrijven/deep-scrape-types";
import { GENERIC_FALLBACK_LISTINGS, SHARED_LISTING_THUMB } from "./generic-listings";
import { buildGenericMakelaarPortalData } from "./makelaar-generic-portal-data";
import { buildDemoAiInsight } from "./ai-insight";
import {
  buildQ2Kpis,
  Q2_PIPELINE_POINTS,
  Q2_VIEWS_POINTS,
} from "./dashboard-q2-data";
import type {
  DemoListingRow,
  ListingStatusStyle,
  MakelaarPortalData,
} from "./types";

const AGENTS = [
  { initials: "MS", name: "Marco Schenkel" },
  { initials: "JV", name: "Jeroen Visser" },
  { initials: "PK", name: "Pieter Koning" },
  { initials: "LB", name: "Lisa Bakker" },
] as const;

function agentName(initials: string): string {
  return AGENTS.find((a) => a.initials === initials)?.name ?? initials;
}

function statusStyle(badge: string): ListingStatusStyle {
  if (/nieuw/i.test(badge)) return "new";
  if (/onder bod/i.test(badge)) return "bid";
  if (/verkocht/i.test(badge)) return "sold";
  return "sale";
}

function listingThumbSrc(
  demoSlug: string,
  index: number,
  imageLocalPath: string | null | undefined,
): string | null {
  if (imageLocalPath) return `/demos/${demoSlug}/${imageLocalPath}`;
  if (demoSlug === "schenkel-makelaardij") {
    return `/demos/schenkel-makelaardij/assets/listings/${index}.webp`;
  }
  return SHARED_LISTING_THUMB(index);
}

function buildListingRows(
  listings: ScrapedListing[],
  demoSlug: string,
): DemoListingRow[] {
  const days = [4, 12, 28, 45, 19, 8, 62, 33];
  const meta = [
    { bedrooms: 4, livingArea: "118 m²", fundaViews: 842 },
    { bedrooms: 5, livingArea: "142 m²", fundaViews: 1204 },
    { bedrooms: 3, livingArea: "96 m²", fundaViews: 2103 },
    { bedrooms: 4, livingArea: "128 m²", fundaViews: 1567 },
    { bedrooms: 3, livingArea: "88 m²", fundaViews: 445 },
    { bedrooms: 5, livingArea: "165 m²", fundaViews: 678 },
  ];
  return listings.map((l, i) => {
    const agent = AGENTS[i % AGENTS.length]!.initials;
    const m = meta[i % meta.length]!;
    return {
      id: `listing-${i}`,
      address: l.title,
      city: l.city,
      price: l.price.replace(/,$/, ""),
      status: l.badge,
      statusStyle: statusStyle(l.badge),
      agent,
      agentName: agentName(agent),
      daysOnMarket: days[i] ?? 21,
      thumbSrc: listingThumbSrc(demoSlug, i, l.imageLocalPath),
      fundaPublished: true,
      websitePublished: i % 5 !== 4,
      publicationStatus: i % 5 === 4 ? "pending" : "live",
      lastSync: i % 3 === 0 ? "2 uur geleden" : "Vandaag 09:15",
      ...m,
    };
  });
}

const FALLBACK_LISTINGS: DemoListingRow[] = [
  {
    id: "listing-0",
    address: "Bloklandweg 46, 7914 PJ",
    city: "Noordscheschut",
    price: "€ 295.000",
    status: "Nieuw",
    statusStyle: "new",
    agent: "MS",
    agentName: "Marco Schenkel",
    daysOnMarket: 4,
    thumbSrc: "/demos/schenkel-makelaardij/assets/listings/0.webp",
    bedrooms: 4,
    livingArea: "118 m²",
    fundaViews: 842,
    fundaPublished: true,
    websitePublished: true,
    publicationStatus: "live",
    lastSync: "Vandaag 09:15",
  },
  {
    id: "listing-1",
    address: "Swammerdamstraat 37, 7908 AH",
    city: "Hoogeveen",
    price: "€ 369.000",
    status: "Nieuw",
    statusStyle: "new",
    agent: "JV",
    agentName: "Jeroen Visser",
    daysOnMarket: 12,
    thumbSrc: "/demos/schenkel-makelaardij/assets/listings/1.webp",
    bedrooms: 5,
    livingArea: "142 m²",
    fundaViews: 1204,
    fundaPublished: true,
    websitePublished: true,
    publicationStatus: "live",
    lastSync: "Vandaag 09:15",
  },
  {
    id: "listing-2",
    address: "Tapuitlaan 44, 7905 CX",
    city: "Hoogeveen",
    price: "€ 415.000",
    status: "Te koop",
    statusStyle: "sale",
    agent: "PK",
    agentName: "Pieter Koning",
    daysOnMarket: 45,
    thumbSrc: "/demos/schenkel-makelaardij/assets/listings/2.webp",
    bedrooms: 3,
    livingArea: "96 m²",
    fundaViews: 2103,
    fundaPublished: true,
    websitePublished: true,
    publicationStatus: "live",
    lastSync: "2 uur geleden",
  },
  {
    id: "listing-3",
    address: "De Plecht 56, 7908 KB",
    city: "Hoogeveen",
    price: "€ 350.000",
    status: "Onder bod",
    statusStyle: "bid",
    agent: "LB",
    agentName: "Lisa Bakker",
    daysOnMarket: 19,
    thumbSrc: "/demos/schenkel-makelaardij/assets/listings/3.webp",
    bedrooms: 4,
    livingArea: "128 m²",
    fundaViews: 1567,
    fundaPublished: true,
    websitePublished: true,
    publicationStatus: "live",
    lastSync: "Vandaag 09:15",
  },
  {
    id: "listing-4",
    address: "Vredenluststraat 13, 7902 BL",
    city: "Hoogeveen",
    price: "€ 289.000",
    status: "Te koop",
    statusStyle: "sale",
    agent: "MS",
    agentName: "Marco Schenkel",
    daysOnMarket: 33,
    thumbSrc: "/demos/schenkel-makelaardij/assets/listings/4.webp",
    bedrooms: 3,
    livingArea: "88 m²",
    fundaViews: 445,
    fundaPublished: true,
    websitePublished: false,
    publicationStatus: "pending",
    lastSync: "Gisteren",
  },
  {
    id: "listing-5",
    address: "Valkenstede 12, 7908 TC",
    city: "Hoogeveen",
    price: "€ 525.000",
    status: "Te koop",
    statusStyle: "sale",
    agent: "JV",
    agentName: "Jeroen Visser",
    daysOnMarket: 8,
    thumbSrc: "/demos/schenkel-makelaardij/assets/listings/5.webp",
    bedrooms: 5,
    livingArea: "165 m²",
    fundaViews: 678,
    fundaPublished: true,
    websitePublished: true,
    publicationStatus: "live",
    lastSync: "Vandaag 09:15",
  },
];

export function buildMakelaarPortalData(
  listings: ScrapedListing[] | undefined,
  demoSlug: string,
): MakelaarPortalData {
  const isSchenkel = demoSlug === "schenkel-makelaardij";
  const rows =
    listings && listings.length > 0
      ? buildListingRows(listings, demoSlug)
      : isSchenkel
        ? FALLBACK_LISTINGS.map((r, i) => ({
            ...r,
            thumbSrc: r.thumbSrc ?? listingThumbSrc(demoSlug, i, null),
          }))
        : GENERIC_FALLBACK_LISTINGS;

  if (!isSchenkel) {
    return buildGenericMakelaarPortalData(rows);
  }

  const onderBod = rows.filter((r) => r.statusStyle === "bid").length;
  const actief = Math.max(25, rows.length + 19);

  const dashboard: MakelaarPortalData = {
    agents: [...AGENTS],
    kpis: [
      {
        label: "Woningen in aanbod",
        value: String(actief),
        trend: "+3",
        trendUp: true,
        chartPoints:
          "0,72 8,68 16,62 24,58 32,52 40,48 48,44 56,40 64,36 72,32 80,28 88,24 96,20",
      },
      {
        label: "Onder bod",
        value: String(Math.max(onderBod, 3)),
        trend: "+1",
        trendUp: true,
        chartPoints:
          "0,80 8,76 16,70 24,66 32,60 40,56 48,52 56,48 64,44 72,40 80,36 88,32 96,28",
      },
      {
        label: "Bezichtigingen (7 dagen)",
        value: "12",
        trend: "+18%",
        trendUp: true,
        chartPoints:
          "0,88 8,82 16,76 24,70 32,64 40,58 48,52 56,46 64,40 72,34 80,28 88,22 96,16",
      },
      {
        label: "Nieuwe leads",
        value: "8",
        trend: "+2",
        trendUp: true,
        chartPoints:
          "0,76 8,72 16,68 24,64 32,58 40,54 48,50 56,46 64,42 72,38 80,34 88,30 96,26",
      },
      {
        label: "Taxaties lopend",
        value: "4",
        trend: "0",
        trendUp: true,
        chartPoints:
          "0,64 8,64 16,62 24,60 32,58 40,56 48,54 56,52 64,50 72,48 80,46 88,44 96,42",
      },
      {
        label: "Gem. dagen op markt",
        value: "68",
        trend: "-5",
        trendUp: true,
        chartPoints:
          "0,32 8,36 16,40 24,38 32,42 40,44 48,46 56,48 64,50 72,52 80,54 88,56 96,58",
      },
    ],
    listings: rows,
    activities: [
      "Bezichtiging gepland — Tapuitlaan 44, morgen 14:00 (JV)",
      "Bod ontvangen — De Plecht 56, € 350.000 k.k.",
      "Nieuwe lead via website — Swammerdamstraat 37",
      "Taxatierapport opgeleverd — Vredenluststraat 13",
      "Funda-sync voltooid — 25 objecten bijgewerkt",
    ],
    tasks: [
      {
        id: "t1",
        title: "Taxatierapport Bloklandweg 46 afronden",
        due: "Vandaag",
        done: false,
        assignee: "MS",
        assigneeName: "Marco Schenkel",
        property: "Bloklandweg 46",
        priority: "hoog",
        category: "taxatie",
      },
      {
        id: "t2",
        title: "Bezichtiging Swammerdamstraat 37",
        due: "Morgen",
        done: false,
        assignee: "JV",
        assigneeName: "Jeroen Visser",
        property: "Swammerdamstraat 37",
        priority: "hoog",
        category: "bezichtiging",
      },
      {
        id: "t3",
        title: "Verkoopbrochure Valkenstede 12",
        due: "Deze week",
        done: true,
        assignee: "JV",
        assigneeName: "Jeroen Visser",
        property: "Valkenstede 12",
        priority: "normaal",
        category: "marketing",
      },
      {
        id: "t4",
        title: "NVM-marktupdate Q2 delen met team",
        due: "Vrijdag",
        done: false,
        assignee: "MS",
        assigneeName: "Marco Schenkel",
        priority: "normaal",
        category: "marketing",
      },
      {
        id: "t5",
        title: "Wwft-check Familie de Vries",
        due: "Vandaag",
        done: false,
        assignee: "MS",
        assigneeName: "Marco Schenkel",
        property: "Bloklandweg 46",
        priority: "hoog",
        category: "compliance",
      },
      {
        id: "t6",
        title: "Kadaster-uittreksel Tapuitlaan 44",
        due: "Morgen",
        done: false,
        assignee: "PK",
        assigneeName: "Pieter Koning",
        property: "Tapuitlaan 44",
        priority: "normaal",
        category: "document",
      },
      {
        id: "t7",
        title: "Biedlogboek De Plecht exporteren",
        due: "Deze week",
        done: false,
        assignee: "LB",
        assigneeName: "Lisa Bakker",
        property: "De Plecht 56",
        priority: "normaal",
        category: "compliance",
      },
      {
        id: "t8",
        title: "Verkoper-portaal Valkenstede: NVM-vragenlijst",
        due: "24 mei",
        done: false,
        assignee: "JV",
        assigneeName: "Jeroen Visser",
        property: "Valkenstede 12",
        priority: "laag",
        category: "document",
      },
    ],
    pipelinePoints: Q2_PIPELINE_POINTS,
    viewsPoints: Q2_VIEWS_POINTS,
    aiInsight: buildDemoAiInsight({
      businessName: "Schenkel Makelaardij",
      regionLabel: "Hoogeveen & Zuid-West Drenthe",
      isSchenkel: true,
    }),
    leads: [
      {
        id: "lead-1",
        name: "Familie de Vries",
        type: "verkoper",
        stage: "onderhandeling",
        source: "Website",
        property: "Bloklandweg 46",
        agent: "MS",
        agentName: "Marco Schenkel",
        email: "devries@email.nl",
        phone: "06-12345678",
        lastContact: "Gisteren",
        score: 92,
      },
      {
        id: "lead-2",
        name: "S. Jansen",
        type: "koper",
        stage: "bezichtiging",
        source: "Funda",
        property: "Tapuitlaan 44",
        agent: "PK",
        agentName: "Pieter Koning",
        email: "s.jansen@email.nl",
        phone: "06-87654321",
        lastContact: "Vandaag",
        score: 78,
      },
      {
        id: "lead-3",
        name: "R. Meijer",
        type: "zoeker",
        stage: "contact",
        source: "Funda",
        property: undefined,
        agent: "JV",
        agentName: "Jeroen Visser",
        email: "meijer@email.nl",
        phone: "06-11223344",
        lastContact: "2 dagen",
        score: 65,
      },
      {
        id: "lead-4",
        name: "M. van Dijk",
        type: "koper",
        stage: "nieuw",
        source: "Website",
        property: "Swammerdamstraat 37",
        agent: "JV",
        agentName: "Jeroen Visser",
        email: "vandijk@email.nl",
        phone: "06-55667788",
        lastContact: "Vandaag",
        score: 88,
      },
      {
        id: "lead-5",
        name: "E. Bakker",
        type: "verkoper",
        stage: "contact",
        source: "Doorverwijzing",
        property: "Valkenstede 12",
        agent: "JV",
        agentName: "Jeroen Visser",
        email: "bakker@email.nl",
        phone: "06-99887766",
        lastContact: "3 dagen",
        score: 71,
      },
      {
        id: "lead-6",
        name: "P. Smit",
        type: "zoeker",
        stage: "nieuw",
        source: "Funda",
        property: undefined,
        agent: "LB",
        agentName: "Lisa Bakker",
        email: "smit@email.nl",
        phone: "06-44332211",
        lastContact: "Vandaag",
        score: 54,
      },
      {
        id: "lead-7",
        name: "Familie Hoekstra",
        type: "koper",
        stage: "onderhandeling",
        source: "Bezichtiging",
        property: "De Plecht 56",
        agent: "LB",
        agentName: "Lisa Bakker",
        email: "hoekstra@email.nl",
        phone: "06-22113344",
        lastContact: "Gisteren",
        score: 95,
      },
      {
        id: "lead-8",
        name: "A. Veenstra",
        type: "verkoper",
        stage: "afgerond",
        source: "Website",
        property: "Vredenluststraat 13",
        agent: "MS",
        agentName: "Marco Schenkel",
        email: "veenstra@email.nl",
        phone: "06-66778899",
        lastContact: "1 week",
        score: 40,
      },
    ],
    viewings: [
      {
        id: "view-1",
        date: "Vandaag",
        time: "14:00",
        property: "Tapuitlaan 44",
        city: "Hoogeveen",
        contact: "S. Jansen",
        agent: "PK",
        agentName: "Pieter Koning",
        status: "bevestigd",
        attendees: 2,
      },
      {
        id: "view-2",
        date: "Morgen",
        time: "10:30",
        property: "Swammerdamstraat 37",
        city: "Hoogeveen",
        contact: "M. van Dijk",
        agent: "JV",
        agentName: "Jeroen Visser",
        status: "gepland",
        attendees: 1,
      },
      {
        id: "view-3",
        date: "Morgen",
        time: "16:00",
        property: "De Plecht 56",
        city: "Hoogeveen",
        contact: "Familie Hoekstra",
        agent: "LB",
        agentName: "Lisa Bakker",
        status: "bevestigd",
        attendees: 3,
      },
      {
        id: "view-4",
        date: "22 mei",
        time: "11:00",
        property: "Bloklandweg 46",
        city: "Noordscheschut",
        contact: "R. Meijer",
        agent: "MS",
        agentName: "Marco Schenkel",
        status: "gepland",
        attendees: 2,
      },
      {
        id: "view-5",
        date: "23 mei",
        time: "13:30",
        property: "Valkenstede 12",
        city: "Hoogeveen",
        contact: "E. Bakker",
        agent: "JV",
        agentName: "Jeroen Visser",
        status: "gepland",
        attendees: 1,
      },
      {
        id: "view-6",
        date: "20 mei",
        time: "15:00",
        property: "Vredenluststraat 13",
        city: "Hoogeveen",
        contact: "P. Smit",
        agent: "MS",
        agentName: "Marco Schenkel",
        status: "afgerond",
        attendees: 2,
      },
    ],
    appraisals: [
      {
        id: "tax-1",
        address: "Bloklandweg 46, 7914 PJ",
        city: "Noordscheschut",
        client: "Familie de Vries",
        status: "rapport",
        dueDate: "Vandaag",
        agent: "MS",
        agentName: "Marco Schenkel",
        indicativeValue: "€ 295.000",
      },
      {
        id: "tax-2",
        address: "Vredenluststraat 13, 7902 BL",
        city: "Hoogeveen",
        client: "A. Veenstra",
        status: "opgeleverd",
        dueDate: "15 mei",
        agent: "MS",
        agentName: "Marco Schenkel",
        indicativeValue: "€ 289.000",
      },
      {
        id: "tax-3",
        address: "Valkenstede 12, 7908 TC",
        city: "Hoogeveen",
        client: "E. Bakker",
        status: "opname",
        dueDate: "24 mei",
        agent: "JV",
        agentName: "Jeroen Visser",
        indicativeValue: "€ 510.000",
      },
      {
        id: "tax-4",
        address: "Kerkstraat 8, 7911 AA",
        city: "Nieuweroord",
        client: "Gemeente Midden-Drenthe",
        status: "intake",
        dueDate: "28 mei",
        agent: "PK",
        agentName: "Pieter Koning",
      },
    ],
    reportMetrics: [
      { label: "Omzet Q2 (prognose)", value: "€ 186.400", change: "+12%", positive: true },
      { label: "Conversie lead → bezichtiging", value: "34%", change: "+4%", positive: true },
      { label: "Gem. verkooptijd", value: "68 dagen", change: "-5 dagen", positive: true },
      { label: "Funda-weergaven (30d)", value: "12.840", change: "+22%", positive: true },
      { label: "NPS verkopers", value: "9,1", change: "+0,3", positive: true },
      { label: "Openstaande taken team", value: "14", change: "-3", positive: true },
    ],
    documents: [
      {
        id: "doc-1",
        name: "Verkoopbrochure Tapuitlaan 44.pdf",
        type: "pdf",
        size: "2,4 MB",
        uploadedAt: "20 mei",
        listingId: "listing-2",
        listingAddress: "Tapuitlaan 44",
      },
      {
        id: "doc-2",
        name: "Energielabel Tapuitlaan 44.pdf",
        type: "pdf",
        size: "180 KB",
        uploadedAt: "18 mei",
        listingId: "listing-2",
        listingAddress: "Tapuitlaan 44",
      },
      {
        id: "doc-3",
        name: "Kadaster-uittreksel Bloklandweg 46.pdf",
        type: "pdf",
        size: "420 KB",
        uploadedAt: "Vandaag",
        listingId: "listing-0",
        listingAddress: "Bloklandweg 46",
      },
      {
        id: "doc-4",
        name: "Taxatierapport concept Vredenluststraat 13.docx",
        type: "doc",
        size: "890 KB",
        uploadedAt: "Gisteren",
        listingId: "listing-4",
        listingAddress: "Vredenluststraat 13",
      },
      {
        id: "doc-5",
        name: "Plattegrond De Plecht 56.pdf",
        type: "pdf",
        size: "1,1 MB",
        uploadedAt: "15 mei",
        listingId: "listing-3",
        listingAddress: "De Plecht 56",
      },
      {
        id: "doc-6",
        name: "Foto's woning Swammerdamstraat 37.zip",
        type: "image",
        size: "24 MB",
        uploadedAt: "19 mei",
        listingId: "listing-1",
        listingAddress: "Swammerdamstraat 37",
      },
      {
        id: "doc-7",
        name: "Verkoopovereenkomst Valkenstede 12.pdf",
        type: "pdf",
        size: "340 KB",
        uploadedAt: "12 mei",
        listingId: "listing-5",
        listingAddress: "Valkenstede 12",
      },
    ],
    sellerChecklists: [
      {
        listingId: "listing-0",
        address: "Bloklandweg 46",
        sellerName: "Familie de Vries",
        progressPct: 85,
        items: [
          { id: "s1", label: "NVM-verkoopvragenlijst", done: true, required: true },
          { id: "s2", label: "Lijst van zaken", done: true, required: true },
          { id: "s3", label: "Energielabel uploaden", done: true, required: true },
          { id: "s4", label: "Identiteitsbewijs verkopers", done: true, required: true },
          { id: "s5", label: "VvE-documenten", done: false, required: false },
        ],
      },
      {
        listingId: "listing-5",
        address: "Valkenstede 12",
        sellerName: "E. Bakker",
        progressPct: 40,
        items: [
          { id: "s6", label: "NVM-verkoopvragenlijst", done: true, required: true },
          { id: "s7", label: "Lijst van zaken", done: false, required: true },
          { id: "s8", label: "Energielabel uploaden", done: false, required: true },
          { id: "s9", label: "Identiteitsbewijs verkopers", done: true, required: true },
          { id: "s10", label: "Foto's aanleveren", done: false, required: true },
        ],
      },
      {
        listingId: "listing-1",
        address: "Swammerdamstraat 37",
        sellerName: "Nog niet gestart",
        progressPct: 10,
        items: [
          { id: "s11", label: "Portaal-uitnodiging verstuurd", done: true, required: true },
          { id: "s12", label: "NVM-verkoopvragenlijst", done: false, required: true },
          { id: "s13", label: "Lijst van zaken", done: false, required: true },
        ],
      },
    ],
    emails: [
      {
        id: "mail-1",
        from: "S. Jansen",
        to: "Pieter Koning",
        subject: "Bezichtiging Tapuitlaan 44 — bevestiging",
        preview: "Bedankt voor de bevestiging van morgen 14:00. Kunnen we 10 minuten eerder?",
        date: "Vandaag 08:42",
        read: false,
        leadId: "lead-2",
        listingAddress: "Tapuitlaan 44",
      },
      {
        id: "mail-2",
        from: "Familie Hoekstra",
        to: "Lisa Bakker",
        subject: "Bod De Plecht 56",
        preview: "Wij willen graag ons bod van € 350.000 k.k. bevestigen met voorbehoud financiering…",
        date: "Gisteren 16:20",
        read: true,
        leadId: "lead-7",
        listingAddress: "De Plecht 56",
      },
      {
        id: "mail-3",
        from: "Funda",
        to: "Kantoor",
        subject: "Sync voltooid — 25 objecten",
        preview: "De synchronisatie met Funda is succesvol afgerond. Geen fouten gemeld.",
        date: "Vandaag 06:00",
        read: true,
      },
      {
        id: "mail-4",
        from: "M. van Dijk",
        to: "Jeroen Visser",
        subject: "Vraag over Swammerdamstraat 37",
        preview: "Is de woning nog beschikbaar voor bezichtiging dit weekend?",
        date: "Vandaag 07:15",
        read: false,
        leadId: "lead-4",
        listingAddress: "Swammerdamstraat 37",
      },
      {
        id: "mail-5",
        from: "E. Bakker",
        to: "Jeroen Visser",
        subject: "Documenten Valkenstede 12",
        preview: "Ik heb de NVM-vragenlijst ingevuld. Lijst van zaken volgt morgen.",
        date: "2 dagen geleden",
        read: true,
        leadId: "lead-5",
        listingAddress: "Valkenstede 12",
      },
    ],
    timeline: [
      {
        id: "tl-1",
        at: "Vandaag 08:42",
        title: "E-mail ontvangen",
        detail: "S. Jansen — bezichtiging Tapuitlaan 44",
        type: "email",
      },
      {
        id: "tl-2",
        at: "Vandaag 06:00",
        title: "Funda-sync voltooid",
        detail: "25 objecten bijgewerkt",
        type: "sync",
      },
      {
        id: "tl-3",
        at: "Gisteren 16:20",
        title: "Bod ontvangen",
        detail: "De Plecht 56 — € 350.000 k.k. (Familie Hoekstra)",
        type: "bid",
      },
      {
        id: "tl-4",
        at: "Gisteren 11:00",
        title: "Bezichtiging afgerond",
        detail: "Vredenluststraat 13 — 2 bezoekers",
        type: "viewing",
      },
      {
        id: "tl-5",
        at: "20 mei",
        title: "Document geüpload",
        detail: "Verkoopbrochure Tapuitlaan 44",
        type: "document",
      },
      {
        id: "tl-6",
        at: "19 mei",
        title: "Nieuwe lead",
        detail: "M. van Dijk via website — Swammerdamstraat 37",
        type: "lead",
      },
    ],
    bidProperty: {
      listingId: "listing-3",
      address: "De Plecht 56, Hoogeveen",
      askingPrice: "€ 350.000 k.k.",
      protocolCompliant: true,
      bids: [
        {
          id: "bid-1",
          amount: "€ 335.000 k.k.",
          amountNum: 335000,
          bidder: "Anoniem (via makelaar)",
          date: "12 mei 14:30",
          status: "vervallen",
          financing: "Hypotheek",
          conditions: "Voorbehoud bouwkundige keuring",
        },
        {
          id: "bid-2",
          amount: "€ 342.500 k.k.",
          amountNum: 342500,
          bidder: "Dhr. Visser",
          date: "16 mei 09:15",
          status: "vervallen",
          financing: "Hypotheek",
        },
        {
          id: "bid-3",
          amount: "€ 348.000 k.k.",
          amountNum: 348000,
          bidder: "Familie Jansen",
          date: "18 mei 18:40",
          status: "vervallen",
          financing: "Contant gedeeltelijk",
        },
        {
          id: "bid-4",
          amount: "€ 350.000 k.k.",
          amountNum: 350000,
          bidder: "Familie Hoekstra",
          date: "Gisteren 16:20",
          status: "actief",
          financing: "Hypotheek",
          conditions: "Voorbehoud financiering 6 weken",
        },
      ],
    },
  };

  return dashboard;
}

/** @deprecated Use buildMakelaarPortalData */
export function buildMakelaarDashboardData(
  listings: ScrapedListing[] | undefined,
  demoSlug: string,
) {
  return buildMakelaarPortalData(listings, demoSlug);
}
